#ifndef __FONT_H
#define __FONT_H


/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.44                      *
*        Compiled Nov 10 2017, 08:53:23                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: 16.c                                                  *
* Font:        ??зоз╓                                                  *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\HTQ\Desktop\123.txt                    *
* Character enabled:   0x20 (32)                                     *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Font16;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_Font16_0020[ 16] = { /* code 0020, SPACE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0021[ 16] = { /* code 0021, EXCLAMATION MARK */
  ________,
  ________,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___X____,
  ___X____,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0022[ 16] = { /* code 0022, QUOTATION MARK */
  ________,
  ________,
  ________,
  __XXXX__,
  __X__X__,
  __X__X__,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0023[ 16] = { /* code 0023, NUMBER SIGN */
  ________,
  ________,
  ________,
  __X___X_,
  __X__X__,
  __X__X__,
  XXXXXXXX,
  __X__X__,
  __X__X__,
  __X__X__,
  XXXXXXXX,
  _X___X__,
  _X__X___,
  _X__X___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0024[ 16] = { /* code 0024, DOLLAR SIGN */
  ________,
  ________,
  ___X____,
  __XXXX__,
  _XXX_X__,
  _X_X_XX_,
  _XXX____,
  __XX____,
  ___XXX__,
  ___X_XX_,
  _X_X_XX_,
  _X_X_XX_,
  _XXX_X__,
  __XXX___,
  ___X____,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0025[ 16] = { /* code 0025, PERCENT SIGN */
  ________,
  ________,
  ________,
  _XX__X__,
  X_X__X__,
  X_X_X___,
  X_XXX___,
  _XX_X___,
  ___X_XX_,
  ___XX_X_,
  __X_X_X_,
  __X_X_X_,
  _X__X_X_,
  _X___XX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0026[ 16] = { /* code 0026, AMPERSAND */
  ________,
  ________,
  ________,
  __XXX___,
  __X_XX__,
  __X_XX__,
  __X_X___,
  __XX____,
  _XXX____,
  _X_X__X_,
  XX__X_X_,
  XX___XX_,
  _XX_XXXX,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0027[ 16] = { /* code 0027, APOSTROPHE */
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  ___X____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0028[ 16] = { /* code 0028, LEFT PARENTHESIS */
  ________,
  ________,
  ______X_,
  _____X__,
  ____XX__,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  _____X__,
  _____X__,
  ______X_,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0029[ 16] = { /* code 0029, RIGHT PARENTHESIS */
  ________,
  ________,
  _X______,
  __X_____,
  __X_____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  __X_____,
  _XX_____,
  XX______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_002A[ 16] = { /* code 002A, ASTERISK */
  ________,
  ________,
  ________,
  ___XX___,
  ___XX___,
  _XXXXXX_,
  ___XX___,
  __XXXX__,
  _X_XX_X_,
  ___XX___,
  ___XX___,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_002B[ 16] = { /* code 002B, PLUS SIGN */
  ________,
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  ___X____,
  XXXXXXXX,
  ___X____,
  ___X____,
  ___X____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_002C[ 16] = { /* code 002C, COMMA */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  __X_____,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_Font16_002D[ 16] = { /* code 002D, HYPHEN-MINUS */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXXX_,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_002E[ 16] = { /* code 002E, FULL STOP */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_002F[ 16] = { /* code 002F, SOLIDUS */
  ________,
  ________,
  ________,
  ______X_,
  _____X__,
  _____X__,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  __X_____,
  __X_____,
  _X______,
  X_______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0030[ 16] = { /* code 0030, DIGIT ZERO */
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___XX_,
  __X_XX__,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0031[ 16] = { /* code 0031, DIGIT ONE */
  ________,
  ________,
  ________,
  ____X___,
  ___XX___,
  _XXXX___,
  _X_XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0032[ 16] = { /* code 0032, DIGIT TWO */
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  _X____X_,
  _____XX_,
  _____X__,
  ____XX__,
  ____X___,
  ___X____,
  __X_____,
  _XXXXXX_,
  _XXXXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0033[ 16] = { /* code 0033, DIGIT THREE */
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  _X____X_,
  _____XX_,
  ____XX__,
  ____XX__,
  _____XX_,
  ______X_,
  _X____X_,
  _XX__X__,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0034[ 16] = { /* code 0034, DIGIT FOUR */
  ________,
  ________,
  ________,
  _____X__,
  ____XX__,
  ___XXX__,
  ___X_X__,
  __X__X__,
  _XX__X__,
  _X___X__,
  XXXXXXXX,
  _____X__,
  _____X__,
  _____X__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0035[ 16] = { /* code 0035, DIGIT FIVE */
  ________,
  ________,
  ________,
  __XXXXX_,
  _XX_____,
  _X______,
  _X_X____,
  _XXXXX__,
  _X___XX_,
  ______X_,
  ______X_,
  XX___XX_,
  _XX_XX__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0036[ 16] = { /* code 0036, DIGIT SIX */
  ________,
  ________,
  ________,
  ____X___,
  ___XX___,
  ___X____,
  __XX____,
  _XXXXX__,
  _XX___X_,
  _X____XX,
  _X____XX,
  _X____X_,
  _XX__XX_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0037[ 16] = { /* code 0037, DIGIT SEVEN */
  ________,
  ________,
  ________,
  _XXXXXX_,
  ______X_,
  _____XX_,
  _____X__,
  ____XX__,
  ____X___,
  ___XX___,
  ___X____,
  ___X____,
  __XX____,
  __XX____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0038[ 16] = { /* code 0038, DIGIT EIGHT */
  ________,
  ________,
  ________,
  __XXXX__,
  _X___XX_,
  _X____X_,
  _X___XX_,
  _XXXXX__,
  _XXXXX__,
  _X____X_,
  XX____X_,
  _X____X_,
  _XX__XX_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0039[ 16] = { /* code 0039, DIGIT NINE */
  ________,
  ________,
  ________,
  __XXXX__,
  _X___XX_,
  XX____X_,
  XX____X_,
  XX___XX_,
  _XX_XX__,
  __XXXX__,
  ____X___,
  ___XX___,
  ___X____,
  __XX____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_003A[ 16] = { /* code 003A, COLON */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___XX___,
  ________,
  ________,
  ________,
  ___XX___,
  ___X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_003B[ 16] = { /* code 003B, SEMICOLON */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___XX___,
  ________,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ___X____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_Font16_003C[ 16] = { /* code 003C, LESS-THAN SIGN */
  ________,
  ________,
  ________,
  ______X_,
  _____X__,
  ____X___,
  ___X____,
  _XX_____,
  _X______,
  __X_____,
  ___X____,
  ____X___,
  _____X__,
  ______X_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_003D[ 16] = { /* code 003D, EQUALS SIGN */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXXX_,
  ________,
  ________,
  ________,
  XXXXXXX_,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_003E[ 16] = { /* code 003E, GREATER-THAN SIGN */
  ________,
  ________,
  ________,
  _X______,
  __X_____,
  ___X____,
  ____X___,
  _____X__,
  ______X_,
  _____X__,
  ____X___,
  ___X____,
  _XX_____,
  _X______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_003F[ 16] = { /* code 003F, QUESTION MARK */
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  _X___XX_,
  _____XX_,
  ____XX__,
  ____X___,
  ___X____,
  ________,
  ________,
  ___XX___,
  ___X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0040[ 16] = { /* code 0040, COMMERCIAL AT */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  X__XXXX_,
  X__X_XX_,
  X_X__XX_,
  X_X_X_X_,
  X_X_X_X_,
  X_X_X_X_,
  X__X_X__,
  _X______,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0041[ 16] = { /* code 0041, LATIN CAPITAL LETTER A */
  ________,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ___XX___,
  __XXXX__,
  __X__X__,
  __X__X__,
  _XXXXX__,
  _XX__XX_,
  _X____X_,
  _X____X_,
  XX____XX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0042[ 16] = { /* code 0042, LATIN CAPITAL LETTER B */
  ________,
  ________,
  ________,
  _XXXXX__,
  _X___XX_,
  _X____X_,
  _X____X_,
  _XXXXX__,
  _XXXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  _XXXXXX_,
  _XXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0043[ 16] = { /* code 0043, LATIN CAPITAL LETTER C */
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  _X____X_,
  _X____X_,
  _X______,
  _X______,
  _X____X_,
  _X____X_,
  _XX___X_,
  __XX_XX_,
  ___XXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0044[ 16] = { /* code 0044, LATIN CAPITAL LETTER D */
  ________,
  ________,
  ________,
  _XXXX___,
  _X__XX__,
  _X___XX_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___XX_,
  _XXXXX__,
  _XXX____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0045[ 16] = { /* code 0045, LATIN CAPITAL LETTER E */
  ________,
  ________,
  ________,
  _XXXXXX_,
  _X______,
  _X______,
  _X______,
  _XXXXXX_,
  _XXXXXX_,
  _X______,
  _X______,
  _X______,
  _XXXXXX_,
  _XXXXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0046[ 16] = { /* code 0046, LATIN CAPITAL LETTER F */
  ________,
  ________,
  ________,
  _XXXXXX_,
  _X______,
  _X______,
  _X______,
  _X______,
  _XXXXX__,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0047[ 16] = { /* code 0047, LATIN CAPITAL LETTER G */
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  _X____X_,
  _X____X_,
  _X______,
  _X__XXX_,
  _X__XXX_,
  _X____X_,
  _XX___X_,
  __XX_XX_,
  ___XX_X_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0048[ 16] = { /* code 0048, LATIN CAPITAL LETTER H */
  ________,
  ________,
  ________,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _XXXXXX_,
  _XXXXXX_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0049[ 16] = { /* code 0049, LATIN CAPITAL LETTER I */
  ________,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_004A[ 16] = { /* code 004A, LATIN CAPITAL LETTER J */
  ________,
  ________,
  ________,
  ______X_,
  ______X_,
  ______X_,
  ______X_,
  ______X_,
  ______X_,
  ______X_,
  _X____X_,
  _X___XX_,
  _XXXXX__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_004B[ 16] = { /* code 004B, LATIN CAPITAL LETTER K */
  ________,
  ________,
  ________,
  _X___XX_,
  _X___X__,
  _X__X___,
  _X_XX___,
  _XXX____,
  _XXXX___,
  _X__X___,
  _X__XX__,
  _X___X__,
  _X___XX_,
  _X____XX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_004C[ 16] = { /* code 004C, LATIN CAPITAL LETTER L */
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _XXXXXX_,
  _XXXXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_004D[ 16] = { /* code 004D, LATIN CAPITAL LETTER M */
  ________,
  ________,
  ________,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX_XXX_,
  _XXXX_X_,
  _X_XX_X_,
  _X_XX_X_,
  _X_XX_X_,
  _X_XX_X_,
  _X_X__X_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_004E[ 16] = { /* code 004E, LATIN CAPITAL LETTER N */
  ________,
  ________,
  ________,
  _X____X_,
  _XX___X_,
  _XX___X_,
  _XXX__X_,
  _X_X__X_,
  _X_XX_X_,
  _X__X_X_,
  _X__XXX_,
  _X___XX_,
  _X___XX_,
  _X___XX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_004F[ 16] = { /* code 004F, LATIN CAPITAL LETTER O */
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  _X____X_,
  _X____X_,
  XX____X_,
  XX____X_,
  XX____X_,
  _X____X_,
  _X___XX_,
  _XX__X__,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0050[ 16] = { /* code 0050, LATIN CAPITAL LETTER P */
  ________,
  ________,
  ________,
  _XXXXX__,
  _X___XX_,
  _X____X_,
  _X____X_,
  _X____X_,
  _XXXXXX_,
  _XXX____,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0051[ 16] = { /* code 0051, LATIN CAPITAL LETTER Q */
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  _X____X_,
  _X____X_,
  XX____X_,
  XX____X_,
  XX____X_,
  _X__X_X_,
  _X__XXX_,
  _XX__X__,
  ___XXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0052[ 16] = { /* code 0052, LATIN CAPITAL LETTER R */
  ________,
  ________,
  ________,
  _XXXXX__,
  _X___XX_,
  _X____X_,
  _X____X_,
  _X___XX_,
  _XXXXX__,
  _X__X___,
  _X__XX__,
  _X___X__,
  _X___XX_,
  _X____X_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0053[ 16] = { /* code 0053, LATIN CAPITAL LETTER S */
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  _X___XX_,
  _XX_____,
  __XX____,
  ___XXX__,
  _____XX_,
  _X____X_,
  _X____X_,
  _XX__XX_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0054[ 16] = { /* code 0054, LATIN CAPITAL LETTER T */
  ________,
  ________,
  ________,
  _XXXXXX_,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0055[ 16] = { /* code 0055, LATIN CAPITAL LETTER U */
  ________,
  ________,
  ________,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _XX__XX_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0056[ 16] = { /* code 0056, LATIN CAPITAL LETTER V */
  ________,
  ________,
  ________,
  XX____X_,
  _X____X_,
  _X___XX_,
  _XX__XX_,
  _XX__X__,
  __X__X__,
  __X_XX__,
  __XXX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0057[ 16] = { /* code 0057, LATIN CAPITAL LETTER W */
  ________,
  ________,
  ________,
  X__XX_XX,
  XX_XX_X_,
  XX_XX_X_,
  _X_XX_X_,
  _X_XX_X_,
  _XX_X_X_,
  _XX_X_X_,
  _XX__XX_,
  _XX__XX_,
  _XX__X__,
  _XX__X__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0058[ 16] = { /* code 0058, LATIN CAPITAL LETTER X */
  ________,
  ________,
  ________,
  _X___XX_,
  _XX__X__,
  __X__X__,
  __XXX___,
  ___XX___,
  ___XX___,
  __XXX___,
  __X_XX__,
  _XX__X__,
  _X___XX_,
  XX____X_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0059[ 16] = { /* code 0059, LATIN CAPITAL LETTER Y */
  ________,
  ________,
  ________,
  XX____X_,
  _X___XX_,
  _XX__X__,
  __X_XX__,
  __XXX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_005A[ 16] = { /* code 005A, LATIN CAPITAL LETTER Z */
  ________,
  ________,
  ________,
  _XXXXXX_,
  _____XX_,
  _____X__,
  ____XX__,
  ____X___,
  ___X____,
  __XX____,
  __X_____,
  _XX_____,
  _XXXXXX_,
  _XXXXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_005B[ 16] = { /* code 005B, LEFT SQUARE BRACKET */
  ________,
  ___XXXX_,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___XXXX_,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_005C[ 16] = { /* code 005C, REVERSE SOLIDUS */
  ________,
  ________,
  ________,
  _X______,
  __X_____,
  __X_____,
  __X_____,
  ___X____,
  ___X____,
  ____X___,
  ____X___,
  ____X___,
  _____X__,
  _____X__,
  ______X_,
  ______X_};

GUI_CONST_STORAGE unsigned char acGUI_Font16_005D[ 16] = { /* code 005D, RIGHT SQUARE BRACKET */
  ________,
  _XXXX___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  _XXXX___,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_005E[ 16] = { /* code 005E, CIRCUMFLEX ACCENT */
  ________,
  ___XX___,
  __X_XX__,
  _X____X_,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_005F[ 16] = { /* code 005F, LOW LINE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0060[ 16] = { /* code 0060, GRAVE ACCENT */
  ________,
  __XX____,
  ___XX___,
  ____X___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0061[ 16] = { /* code 0061, LATIN SMALL LETTER A */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X___XX_,
  ____XXX_,
  _XXX_XX_,
  _X___XX_,
  _X__XXX_,
  __XXX_X_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0062[ 16] = { /* code 0062, LATIN SMALL LETTER B */
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _XXXXX__,
  _X___XX_,
  _X____X_,
  _X____X_,
  _X___XX_,
  _XX__XX_,
  _X_XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0063[ 16] = { /* code 0063, LATIN SMALL LETTER C */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X___XX_,
  _X______,
  _X______,
  _X____X_,
  _XX__XX_,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0064[ 16] = { /* code 0064, LATIN SMALL LETTER D */
  ________,
  ________,
  ________,
  ______X_,
  ______X_,
  ______X_,
  ______X_,
  _XXXXXX_,
  _X___XX_,
  _X____X_,
  _X____X_,
  _X___XX_,
  _XX__XX_,
  __XXX_X_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0065[ 16] = { /* code 0065, LATIN SMALL LETTER E */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X___XX_,
  _XXXXXX_,
  _X______,
  _X____X_,
  _XX__XX_,
  ___XXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0066[ 16] = { /* code 0066, LATIN SMALL LETTER F */
  ________,
  ________,
  ________,
  ___XXXX_,
  ___X____,
  ___X____,
  ___X____,
  _XXXXXX_,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0067[ 16] = { /* code 0067, LATIN SMALL LETTER G */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXXX_,
  _X___X__,
  _X___X__,
  __XXXX__,
  _X______,
  _XXXXX__,
  _X___XX_,
  _X____X_,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0068[ 16] = { /* code 0068, LATIN SMALL LETTER H */
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X_XXXX_,
  _XX___X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0069[ 16] = { /* code 0069, LATIN SMALL LETTER I */
  ________,
  ________,
  ________,
  ___XX___,
  ___X____,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_006A[ 16] = { /* code 006A, LATIN SMALL LETTER J */
  ________,
  ________,
  ________,
  ____XX__,
  _____X__,
  ________,
  ________,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  _X__XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Font16_006B[ 16] = { /* code 006B, LATIN SMALL LETTER K */
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X__XX__,
  _X_XX___,
  _XXXX___,
  _XX_X___,
  _X___X__,
  _X___XX_,
  _X____X_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_006C[ 16] = { /* code 006C, LATIN SMALL LETTER L */
  ________,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_006D[ 16] = { /* code 006D, LATIN SMALL LETTER M */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXX_XXX,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_006E[ 16] = { /* code 006E, LATIN SMALL LETTER N */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _X_XXXX_,
  _XX___X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_006F[ 16] = { /* code 006F, LATIN SMALL LETTER O */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X___XX_,
  _X____X_,
  _X____X_,
  _X____X_,
  _XX__XX_,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0070[ 16] = { /* code 0070, LATIN SMALL LETTER P */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  _X___XX_,
  _X____X_,
  _X____X_,
  _X___XX_,
  _XX__XX_,
  _X_XX___,
  _X______,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0071[ 16] = { /* code 0071, LATIN SMALL LETTER Q */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXXX_,
  _X___XX_,
  _X____X_,
  _X____X_,
  _X___XX_,
  _XX__XX_,
  __XXX_X_,
  ______X_,
  ______X_};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0072[ 16] = { /* code 0072, LATIN SMALL LETTER R */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __X_XX__,
  __XX____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0073[ 16] = { /* code 0073, LATIN SMALL LETTER S */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  _XX_____,
  ___XXX__,
  _X____X_,
  _XX__XX_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0074[ 16] = { /* code 0074, LATIN SMALL LETTER T */
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  ___X____,
  XXXXXX__,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X__X_,
  ____XXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0075[ 16] = { /* code 0075, LATIN SMALL LETTER U */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___XX_,
  _XX_XXX_,
  __XXX_X_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0076[ 16] = { /* code 0076, LATIN SMALL LETTER V */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _X____X_,
  _XX__XX_,
  __X__X__,
  __X__X__,
  __XXX___,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0077[ 16] = { /* code 0077, LATIN SMALL LETTER W */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX_XX_XX,
  XX_XX_X_,
  _X_XX_X_,
  _XX_X_X_,
  _XX__XX_,
  _XX__X__,
  __X__X__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0078[ 16] = { /* code 0078, LATIN SMALL LETTER X */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX__X__,
  __X_XX__,
  ___XX___,
  ___XX___,
  __XXXX__,
  _XX__X__,
  _X____X_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_0079[ 16] = { /* code 0079, LATIN SMALL LETTER Y */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _X____X_,
  _XX__XX_,
  __X__X__,
  __X__X__,
  __XXX___,
  ___XX___,
  ___XX___,
  ___X____,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_Font16_007A[ 16] = { /* code 007A, LATIN SMALL LETTER Z */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXXX_,
  ____XX__,
  ____X___,
  ___X____,
  __X_____,
  _XX_____,
  _XXXXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_007B[ 16] = { /* code 007B, LEFT CURLY BRACKET */
  ________,
  _____XX_,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____X___,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  _____X__,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_007C[ 16] = { /* code 007C, VERTICAL LINE */
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_Font16_007D[ 16] = { /* code 007D, RIGHT CURLY BRACKET */
  ________,
  _XX_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  ___X____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_007E[ 16] = { /* code 007E, TILDE */
  __X_____,
  _XXX__X_,
  _X__XXX_,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

/* Start of unicode area <CJK Symbols and Punctuation> */
GUI_CONST_STORAGE unsigned char acGUI_Font16_3002[ 32] = { /* code 3002, IDEOGRAPHIC FULL STOP */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XXXX__,________,
  __X__X__,________,
  __XXX___,________,
  ________,________,
  ________,________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Font16_4E0E[ 32] = { /* code 4E0E */
  ________,________,
  ________,________,
  ______X_,________,
  ______X_,________,
  ______X_,_XXX____,
  ______XX,X_______,
  _____X__,________,
  _____X__,__XXX___,
  _____XXX,XX__X___,
  ________,____X___,
  _______X,XXX_X___,
  __XXXXX_,____X___,
  ________,____X___,
  ________,_X_X____,
  ________,__XX____,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_4F4D[ 32] = { /* code 4F4D */
  ________,________,
  ________,________,
  _____X__,________,
  _____X__,XX______,
  ____X___,________,
  ____X___,________,
  ___X____,XXXX____,
  ___X____,________,
  __X_X___,___X____,
  _X__X__X,__X_____,
  ___X___X,__X_____,
  ___X____,_X______,
  ___X____,XXXXXXX_,
  ___X__XX,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_4FE1[ 32] = { /* code 4FE1 */
  ________,________,
  ________,________,
  _____X__,_XX_____,
  ____X___,__X_____,
  ____X___,_____X__,
  ___X__XX,XXXXX___,
  ___X____,________,
  __X_X___,XXX_____,
  _X__X___,________,
  ____X___,XXX_____,
  ____X___,___X____,
  ____X__X,XXX_X___,
  ____X__X,___X____,
  ____X___,XXXXX___,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_52A8[ 32] = { /* code 52A8 */
  ________,________,
  ________,________,
  ________,__XX____,
  ________,__X_____,
  ____XXX_,__X_____,
  ________,__XXXX__,
  _______X,XXX__X__,
  _XXXXXX_,__X__X__,
  ____X___,_X___X__,
  ___X__X_,_X___X__,
  ___XXX_X,X___X___,
  __XX____,X___X___,
  _______X,____X___,
  ______X_,__XX____,
  _____X__,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_5316[ 32] = { /* code 5316 */
  ________,________,
  ________,________,
  ____XX__,X_______,
  ____X___,X_______,
  ____X___,X__X____,
  ___X____,X_XX____,
  ___X____,X_X_____,
  __X_X___,XX______,
  _X__X___,X_______,
  ____X__X,X_______,
  ____XXX_,X_____X_,
  ____X___,X_____X_,
  ____X___,XX___XX_,
  ____X___,__XXXX__,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_5404[ 32] = { /* code 5404 */
  ________,________,
  ______X_,________,
  ______X_,________,
  ______X_,XX______,
  _____X_X,_X______,
  ____XX__,X_______,
  ___X__X_,X_______,
  _______X,X_______,
  ______X_,_X______,
  ____XX__,__XXX___,
  ___X____,XXX_XXX_,
  _XX_XXXX,_XX_____,
  _____X__,_X______,
  _____X__,_X______,
  _____XXX,X_______,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_5927[ 32] = { /* code 5927 */
  ________,________,
  ________,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,_XXXX___,
  ___XXXXX,X_______,
  _______X,________,
  _______X,X_______,
  ______X_,X_______,
  ______X_,_X______,
  _____X__,__X_____,
  ____X___,__XXX___,
  ___X____,_____X__,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_5929[ 32] = { /* code 5929 */
  ________,________,
  ________,________,
  ________,________,
  _____XXX,XX______,
  _______X,________,
  _______X,________,
  _______X,_XXX____,
  ___XXXXX,X_______,
  _______X,________,
  ______XX,________,
  ______X_,X_______,
  _____X__,_X______,
  ____X___,__XX____,
  __XX____,___XXX__,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_5947[ 32] = { /* code 5947 */
  ________,________,
  ________,X_______,
  ________,X_______,
  _______X,XXX_____,
  ______XX,________,
  _______X,XX______,
  ______X_,_X______,
  ______XX,XXXXXXX_,
  __XXXX__,__X_____,
  ____XXXX,X_X_____,
  ____X__X,__X_____,
  _____XX_,__X_____,
  ________,__X_____,
  ________,__X_____,
  ________,XXX_____,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_597D[ 32] = { /* code 597D */
  ________,________,
  ________,________,
  ____X___,________,
  ____X___,_XXXXX__,
  ____X___,____X___,
  ____X_X_,__XX____,
  ____X_X_,__X_____,
  _XXX_XX_,__XXXXX_,
  ___X__XX,XX_X____,
  ____XX__,___X____,
  _____X__,___X____,
  ____X_X_,___X____,
  ___X____,___X____,
  ________,_XX_____,
  ________,__X_____,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_5B50[ 32] = { /* code 5B50 */
  ________,________,
  ________,________,
  ________,XXX_____,
  ____XXXX,__X_____,
  ________,_X______,
  _______X,X_______,
  ________,X__XXX__,
  ____XXXX,XXX_____,
  __XX____,X_______,
  ________,X_______,
  ________,X_______,
  ________,X_______,
  ________,X_______,
  _____X__,X_______,
  ______XX,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_5B66[ 32] = { /* code 5B66 */
  ________,________,
  ________,__XX____,
  _____X_X,__X_____,
  _____X__,_X______,
  ________,_X__X___,
  ____XXXX,X_XXXXX_,
  __XX____,X___X___,
  __X__XXX,XX______,
  _______X,________,
  ________,XXXXXX__,
  __XXXXXX,X_______,
  ________,X_______,
  ________,X_______,
  ________,X_______,
  ______XX,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_5E08[ 32] = { /* code 5E08 */
  ________,________,
  ________,________,
  _____X__,________,
  _____X__,_XXXXX__,
  __X__X__,X_X_____,
  __X__X__,__X_____,
  __X__X_X,XXXXXX__,
  __X__X_X,__X__X__,
  __X_X__X,__X__X__,
  ____X__X,__XX_X__,
  ____X__X,__X_XX__,
  ___X____,__X_____,
  ___X____,__X_____,
  __X_____,__X_____,
  ________,__X_____,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_606F[ 32] = { /* code 606F */
  ________,________,
  _______X,________,
  ______X_,________,
  _____X__,_X______,
  _____XXX,XXX_____,
  _____X_X,__X_____,
  _____XX_,_X______,
  _____XXX,_X______,
  _____X__,XX______,
  _____XXX,_X______,
  _______X,X___XXX_,
  __X_____,X_______,
  __X__X__,___X____,
  __X___X_,___XX___,
  _______X,XXXX____,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_60A8[ 32] = { /* code 60A8 */
  ________,________,
  ________,________,
  _____X__,X_______,
  ____X___,X__XX___,
  ____X__X,_XX_X___,
  ___XX_X_,_X_X____,
  __X_X__X,_X_X____,
  ____X_X_,_X__X___,
  ____X_X_,_X______,
  ____X___,_X______,
  ___X___X,X___XXX_,
  ___X_X__,X_____X_,
  ___X_X__,___X____,
  __X___XX,X__XX___,
  ________,_XX_____,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_6211[ 32] = { /* code 6211 */
  ________,________,
  _______X,X_______,
  ________,X_______,
  ________,X__X____,
  ______X_,X_______,
  _____X__,X_______,
  _____X__,XXX_____,
  ______XX,X_______,
  __XXXX__,_X_XX___,
  ______X_,_X_X____,
  ____XX__,__X_____,
  _XXX_X__,_XX_____,
  _____X_X,X__X__X_,
  ____XX__,____XXX_,
  ________,_____XX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_6280[ 32] = { /* code 6280 */
  ________,________,
  ____X___,________,
  _____X__,__X_____,
  _____X__,__X_____,
  ____X___,__XXX___,
  _____XX_,XXX_____,
  __XXX___,_X______,
  ____X_X_,_X_X____,
  _____X_X,XXXX____,
  ___XX__X,___X____,
  _XX_X___,XXX_____,
  ____X___,__X_____,
  ____X___,_X_X____,
  ____X_XX,X___XXX_,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_662F[ 32] = { /* code 662F */
  ________,________,
  ________,________,
  _____XXX,XXX_____,
  ______X_,__X_____,
  ______XX,__X_____,
  ______X_,_X______,
  _______X,X_______,
  ________,XXXXX___,
  __XXXXXX,X_______,
  _____X__,X_X_____,
  ____XX__,XX______,
  ____X_XX,X_______,
  ___X____,X_______,
  __X_____,_XXX____,
  ________,___XXX__,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_68A6[ 32] = { /* code 68A6 */
  ________,________,
  _____X__,__X_____,
  _____X__,__X_____,
  _____X__,__X_X___,
  ___XXXXX,XXXX____,
  ____XXX_,_XXX____,
  ____XXX_,X_X_XX__,
  ___X_X_X,__X___X_,
  _____X_X,________,
  _______X,XXX_____,
  ______X_,__X_____,
  _____XX_,_X______,
  _______X,X_______,
  _______X,________,
  _____XX_,________,
  ___XX___,________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_6B22[ 32] = { /* code 6B22 */
  ________,________,
  ________,________,
  ________,_X______,
  ________,_X______,
  ________,X_______,
  ___XXX__,X_XXX___,
  __X__X_X,_X_X____,
  __X_X___,X_______,
  ___XX___,X_______,
  ____X___,X_______,
  ___X_X__,XX______,
  ___X_X__,X_X_____,
  __X____X,___X____,
  ______X_,___XX___,
  ________,_____X__,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_6D25[ 32] = { /* code 6D25 */
  ________,________,
  ________,XX______,
  ________,X_______,
  ____X___,XXXX____,
  ______XX,X__X____,
  ________,XXXXXX__,
  __X__XXX,X_X_____,
  ________,XXXX____,
  _______X,X_______,
  ___X__XX,XXX_____,
  __X_____,X__XXX__,
  __X_XXXX,XXX_____,
  __X_____,X_______,
  __X_____,X_______,
  ________,X_______,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_7535[ 32] = { /* code 7535 */
  ________,________,
  ________,________,
  ______XX,________,
  ______X_,________,
  ______X_,_XXX____,
  __XXXXXX,X_XX____,
  ___X__X_,__XX____,
  ___X_XXX,X_X_____,
  ___XX_X_,__X_____,
  ___X__XX,XX______,
  ____XXX_,________,
  ______X_,_____X__,
  ______X_,_____X__,
  _______X,XXXXXX__,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_79D1[ 32] = { /* code 79D1 */
  ________,________,
  ________,________,
  ______X_,___X____,
  _____X__,___X____,
  ___XXX__,_X_X____,
  _____X__,___X____,
  ____XXXX,XX_X____,
  _XXXXX__,_X_X____,
  ____XXX_,___XXXX_,
  ___X_X_X,XXXX____,
  __X__X__,___X____,
  _X___X__,___X____,
  _____X__,___X____,
  _____X__,___X____,
  ________,___X____,
  ________,___X____};

GUI_CONST_STORAGE unsigned char acGUI_Font16_8001[ 32] = { /* code 8001 */
  ________,________,
  ______X_,________,
  _______X,________,
  _______X,___X____,
  _______X,XXXX____,
  _____XXX,__X_____,
  _______X,_X_XXXX_,
  ______XX,XXX_____,
  __XXXX_X,________,
  ______X_,__X_____,
  _____XX_,XX______,
  ____X_XX,________,
  __XX__X_,___X____,
  ______XX,__XXX___,
  ________,XX______,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_81EA[ 32] = { /* code 81EA */
  ________,________,
  _______X,________,
  _______X,________,
  ______X_,________,
  ______X_,_XX_____,
  ____XX_X,X_XX____,
  ____X___,___X____,
  ____X___,___X____,
  _____XXX,___X____,
  ____X___,___X____,
  _____XXX,X__X____,
  ____X___,___X____,
  ____X___,XX_X____,
  _____XXX,__XX____,
  ________,__X_____,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_8303[ 32] = { /* code 8303 */
  ________,________,
  ________,________,
  _____X__,_XX_____,
  _____X__,_X_XX___,
  __XXXXXX,XXX_____,
  ________,X_______,
  ________,________,
  ____X__X,XXXX____,
  __X____X,__X_____,
  ___X___X,__X_____,
  _______X,_XX_____,
  ____X__X,________,
  ___X___X,______X_,
  __XX____,XX_XXXX_,
  ________,__X_____,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_8C22[ 32] = { /* code 8C22 */
  ________,________,
  ________,X_______,
  ________,X___X___,
  ___XX__X,____X___,
  ______X_,XX__X___,
  ______XX,X___X___,
  ___XX_X_,X___X___,
  _XXX__XX,X_XXXX__,
  ___X__X_,X___X___,
  ___X_X_X,X_X_X___,
  ___X__X_,X___X___,
  ___XX_X_,X___X___,
  __XX_X__,X___X___,
  ____X__X,X__XX___,
  ________,X___X___,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_8FCE[ 32] = { /* code 8FCE */
  ________,________,
  ________,________,
  ________,XX______,
  ___XX___,X_______,
  ____X__X,___XXX__,
  ______X_,_XX_X___,
  ______X_,_X__X___,
  __XXX_X_,XX__X___,
  ___X__XX,_X__X___,
  ___X__X_,_X______,
  ____X___,_X______,
  _XXXX___,_X______,
  _____XXX,_X______,
  ________,XXXXXXX_,
  ________,___X____,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_9662[ 32] = { /* code 9662 */
  ________,________,
  ________,________,
  ________,XX______,
  __XXXX__,_X______,
  __X_X___,_XXXX___,
  __X_X__X,X_______,
  __X_X_X_,__X_____,
  __X_XX_X,XX______,
  __X__X__,__XX____,
  __X___XX,XX______,
  __X_____,XX______,
  __X____X,_X______,
  __X___X_,_X___X__,
  __X__X__,__XXXXX_,
  ________,________,
  ________,________};

/* Start of unicode area <Halfwidth and Fullwidth Forms> */
GUI_CONST_STORAGE unsigned char acGUI_Font16_FF01[ 32] = { /* code FF01, FULLWIDTH EXCLAMATION MARK */
  ________,________,
  ________,________,
  ________,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____X___,________,
  ____X___,________,
  ________,________,
  ________,________,
  ____XX__,________,
  ____XX__,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Font16_CharInfo[126] = {
   {   8,   8,  1, acGUI_Font16_0020 } /* code 0020 */
  ,{   8,   8,  1, acGUI_Font16_0021 } /* code 0021 */
  ,{   8,   8,  1, acGUI_Font16_0022 } /* code 0022 */
  ,{   8,   8,  1, acGUI_Font16_0023 } /* code 0023 */
  ,{   8,   8,  1, acGUI_Font16_0024 } /* code 0024 */
  ,{   8,   8,  1, acGUI_Font16_0025 } /* code 0025 */
  ,{   8,   8,  1, acGUI_Font16_0026 } /* code 0026 */
  ,{   8,   8,  1, acGUI_Font16_0027 } /* code 0027 */
  ,{   8,   8,  1, acGUI_Font16_0028 } /* code 0028 */
  ,{   8,   8,  1, acGUI_Font16_0029 } /* code 0029 */
  ,{   8,   8,  1, acGUI_Font16_002A } /* code 002A */
  ,{   8,   8,  1, acGUI_Font16_002B } /* code 002B */
  ,{   8,   8,  1, acGUI_Font16_002C } /* code 002C */
  ,{   8,   8,  1, acGUI_Font16_002D } /* code 002D */
  ,{   8,   8,  1, acGUI_Font16_002E } /* code 002E */
  ,{   8,   8,  1, acGUI_Font16_002F } /* code 002F */
  ,{   8,   8,  1, acGUI_Font16_0030 } /* code 0030 */
  ,{   8,   8,  1, acGUI_Font16_0031 } /* code 0031 */
  ,{   8,   8,  1, acGUI_Font16_0032 } /* code 0032 */
  ,{   8,   8,  1, acGUI_Font16_0033 } /* code 0033 */
  ,{   8,   8,  1, acGUI_Font16_0034 } /* code 0034 */
  ,{   8,   8,  1, acGUI_Font16_0035 } /* code 0035 */
  ,{   8,   8,  1, acGUI_Font16_0036 } /* code 0036 */
  ,{   8,   8,  1, acGUI_Font16_0037 } /* code 0037 */
  ,{   8,   8,  1, acGUI_Font16_0038 } /* code 0038 */
  ,{   8,   8,  1, acGUI_Font16_0039 } /* code 0039 */
  ,{   8,   8,  1, acGUI_Font16_003A } /* code 003A */
  ,{   8,   8,  1, acGUI_Font16_003B } /* code 003B */
  ,{   8,   8,  1, acGUI_Font16_003C } /* code 003C */
  ,{   8,   8,  1, acGUI_Font16_003D } /* code 003D */
  ,{   8,   8,  1, acGUI_Font16_003E } /* code 003E */
  ,{   8,   8,  1, acGUI_Font16_003F } /* code 003F */
  ,{   8,   8,  1, acGUI_Font16_0040 } /* code 0040 */
  ,{   8,   8,  1, acGUI_Font16_0041 } /* code 0041 */
  ,{   8,   8,  1, acGUI_Font16_0042 } /* code 0042 */
  ,{   8,   8,  1, acGUI_Font16_0043 } /* code 0043 */
  ,{   8,   8,  1, acGUI_Font16_0044 } /* code 0044 */
  ,{   8,   8,  1, acGUI_Font16_0045 } /* code 0045 */
  ,{   8,   8,  1, acGUI_Font16_0046 } /* code 0046 */
  ,{   8,   8,  1, acGUI_Font16_0047 } /* code 0047 */
  ,{   8,   8,  1, acGUI_Font16_0048 } /* code 0048 */
  ,{   8,   8,  1, acGUI_Font16_0049 } /* code 0049 */
  ,{   8,   8,  1, acGUI_Font16_004A } /* code 004A */
  ,{   8,   8,  1, acGUI_Font16_004B } /* code 004B */
  ,{   8,   8,  1, acGUI_Font16_004C } /* code 004C */
  ,{   8,   8,  1, acGUI_Font16_004D } /* code 004D */
  ,{   8,   8,  1, acGUI_Font16_004E } /* code 004E */
  ,{   8,   8,  1, acGUI_Font16_004F } /* code 004F */
  ,{   8,   8,  1, acGUI_Font16_0050 } /* code 0050 */
  ,{   8,   8,  1, acGUI_Font16_0051 } /* code 0051 */
  ,{   8,   8,  1, acGUI_Font16_0052 } /* code 0052 */
  ,{   8,   8,  1, acGUI_Font16_0053 } /* code 0053 */
  ,{   8,   8,  1, acGUI_Font16_0054 } /* code 0054 */
  ,{   8,   8,  1, acGUI_Font16_0055 } /* code 0055 */
  ,{   8,   8,  1, acGUI_Font16_0056 } /* code 0056 */
  ,{   8,   8,  1, acGUI_Font16_0057 } /* code 0057 */
  ,{   8,   8,  1, acGUI_Font16_0058 } /* code 0058 */
  ,{   8,   8,  1, acGUI_Font16_0059 } /* code 0059 */
  ,{   8,   8,  1, acGUI_Font16_005A } /* code 005A */
  ,{   8,   8,  1, acGUI_Font16_005B } /* code 005B */
  ,{   8,   8,  1, acGUI_Font16_005C } /* code 005C */
  ,{   8,   8,  1, acGUI_Font16_005D } /* code 005D */
  ,{   8,   8,  1, acGUI_Font16_005E } /* code 005E */
  ,{   8,   8,  1, acGUI_Font16_005F } /* code 005F */
  ,{   8,   8,  1, acGUI_Font16_0060 } /* code 0060 */
  ,{   8,   8,  1, acGUI_Font16_0061 } /* code 0061 */
  ,{   8,   8,  1, acGUI_Font16_0062 } /* code 0062 */
  ,{   8,   8,  1, acGUI_Font16_0063 } /* code 0063 */
  ,{   8,   8,  1, acGUI_Font16_0064 } /* code 0064 */
  ,{   8,   8,  1, acGUI_Font16_0065 } /* code 0065 */
  ,{   8,   8,  1, acGUI_Font16_0066 } /* code 0066 */
  ,{   8,   8,  1, acGUI_Font16_0067 } /* code 0067 */
  ,{   8,   8,  1, acGUI_Font16_0068 } /* code 0068 */
  ,{   8,   8,  1, acGUI_Font16_0069 } /* code 0069 */
  ,{   8,   8,  1, acGUI_Font16_006A } /* code 006A */
  ,{   8,   8,  1, acGUI_Font16_006B } /* code 006B */
  ,{   8,   8,  1, acGUI_Font16_006C } /* code 006C */
  ,{   8,   8,  1, acGUI_Font16_006D } /* code 006D */
  ,{   8,   8,  1, acGUI_Font16_006E } /* code 006E */
  ,{   8,   8,  1, acGUI_Font16_006F } /* code 006F */
  ,{   8,   8,  1, acGUI_Font16_0070 } /* code 0070 */
  ,{   8,   8,  1, acGUI_Font16_0071 } /* code 0071 */
  ,{   8,   8,  1, acGUI_Font16_0072 } /* code 0072 */
  ,{   8,   8,  1, acGUI_Font16_0073 } /* code 0073 */
  ,{   8,   8,  1, acGUI_Font16_0074 } /* code 0074 */
  ,{   8,   8,  1, acGUI_Font16_0075 } /* code 0075 */
  ,{   8,   8,  1, acGUI_Font16_0076 } /* code 0076 */
  ,{   8,   8,  1, acGUI_Font16_0077 } /* code 0077 */
  ,{   8,   8,  1, acGUI_Font16_0078 } /* code 0078 */
  ,{   8,   8,  1, acGUI_Font16_0079 } /* code 0079 */
  ,{   8,   8,  1, acGUI_Font16_007A } /* code 007A */
  ,{   8,   8,  1, acGUI_Font16_007B } /* code 007B */
  ,{   8,   8,  1, acGUI_Font16_007C } /* code 007C */
  ,{   8,   8,  1, acGUI_Font16_007D } /* code 007D */
  ,{   8,   8,  1, acGUI_Font16_007E } /* code 007E */
  ,{  16,  16,  2, acGUI_Font16_3002 } /* code 3002 */
  ,{  16,  16,  2, acGUI_Font16_4E0E } /* code 4E0E */
  ,{  16,  16,  2, acGUI_Font16_4F4D } /* code 4F4D */
  ,{  16,  16,  2, acGUI_Font16_4FE1 } /* code 4FE1 */
  ,{  16,  16,  2, acGUI_Font16_52A8 } /* code 52A8 */
  ,{  16,  16,  2, acGUI_Font16_5316 } /* code 5316 */
  ,{  16,  16,  2, acGUI_Font16_5404 } /* code 5404 */
  ,{  16,  16,  2, acGUI_Font16_5927 } /* code 5927 */
  ,{  16,  16,  2, acGUI_Font16_5929 } /* code 5929 */
  ,{  16,  16,  2, acGUI_Font16_5947 } /* code 5947 */
  ,{  16,  16,  2, acGUI_Font16_597D } /* code 597D */
  ,{  16,  16,  2, acGUI_Font16_5B50 } /* code 5B50 */
  ,{  16,  16,  2, acGUI_Font16_5B66 } /* code 5B66 */
  ,{  16,  16,  2, acGUI_Font16_5E08 } /* code 5E08 */
  ,{  16,  16,  2, acGUI_Font16_606F } /* code 606F */
  ,{  16,  16,  2, acGUI_Font16_60A8 } /* code 60A8 */
  ,{  16,  16,  2, acGUI_Font16_6211 } /* code 6211 */
  ,{  16,  16,  2, acGUI_Font16_6280 } /* code 6280 */
  ,{  16,  16,  2, acGUI_Font16_662F } /* code 662F */
  ,{  16,  16,  2, acGUI_Font16_68A6 } /* code 68A6 */
  ,{  16,  16,  2, acGUI_Font16_6B22 } /* code 6B22 */
  ,{  16,  16,  2, acGUI_Font16_6D25 } /* code 6D25 */
  ,{  16,  16,  2, acGUI_Font16_7535 } /* code 7535 */
  ,{  16,  16,  2, acGUI_Font16_79D1 } /* code 79D1 */
  ,{  16,  16,  2, acGUI_Font16_8001 } /* code 8001 */
  ,{  16,  16,  2, acGUI_Font16_81EA } /* code 81EA */
  ,{  16,  16,  2, acGUI_Font16_8303 } /* code 8303 */
  ,{  16,  16,  2, acGUI_Font16_8C22 } /* code 8C22 */
  ,{  16,  16,  2, acGUI_Font16_8FCE } /* code 8FCE */
  ,{  16,  16,  2, acGUI_Font16_9662 } /* code 9662 */
  ,{  16,  16,  2, acGUI_Font16_FF01 } /* code FF01 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font16_Prop32 = {
   0xFF01 /* first character */
  ,0xFF01 /* last character  */
  ,&GUI_Font16_CharInfo[125] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font16_Prop31 = {
   0x9662 /* first character */
  ,0x9662 /* last character  */
  ,&GUI_Font16_CharInfo[124] /* address of first character */
  ,&GUI_Font16_Prop32 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font16_Prop30 = {
   0x8FCE /* first character */
  ,0x8FCE /* last character  */
  ,&GUI_Font16_CharInfo[123] /* address of first character */
  ,&GUI_Font16_Prop31 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font16_Prop29 = {
   0x8C22 /* first character */
  ,0x8C22 /* last character  */
  ,&GUI_Font16_CharInfo[122] /* address of first character */
  ,&GUI_Font16_Prop30 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font16_Prop28 = {
   0x8303 /* first character */
  ,0x8303 /* last character  */
  ,&GUI_Font16_CharInfo[121] /* address of first character */
  ,&GUI_Font16_Prop29 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font16_Prop27 = {
   0x81EA /* first character */
  ,0x81EA /* last character  */
  ,&GUI_Font16_CharInfo[120] /* address of first character */
  ,&GUI_Font16_Prop28 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font16_Prop26 = {
   0x8001 /* first character */
  ,0x8001 /* last character  */
  ,&GUI_Font16_CharInfo[119] /* address of first character */
  ,&GUI_Font16_Prop27 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font16_Prop25 = {
   0x79D1 /* first character */
  ,0x79D1 /* last character  */
  ,&GUI_Font16_CharInfo[118] /* address of first character */
  ,&GUI_Font16_Prop26 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font16_Prop24 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_Font16_CharInfo[117] /* address of first character */
  ,&GUI_Font16_Prop25 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font16_Prop23 = {
   0x6D25 /* first character */
  ,0x6D25 /* last character  */
  ,&GUI_Font16_CharInfo[116] /* address of first character */
  ,&GUI_Font16_Prop24 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font16_Prop22 = {
   0x6B22 /* first character */
  ,0x6B22 /* last character  */
  ,&GUI_Font16_CharInfo[115] /* address of first character */
  ,&GUI_Font16_Prop23 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font16_Prop21 = {
   0x68A6 /* first character */
  ,0x68A6 /* last character  */
  ,&GUI_Font16_CharInfo[114] /* address of first character */
  ,&GUI_Font16_Prop22 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font16_Prop20 = {
   0x662F /* first character */
  ,0x662F /* last character  */
  ,&GUI_Font16_CharInfo[113] /* address of first character */
  ,&GUI_Font16_Prop21 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font16_Prop19 = {
   0x6280 /* first character */
  ,0x6280 /* last character  */
  ,&GUI_Font16_CharInfo[112] /* address of first character */
  ,&GUI_Font16_Prop20 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font16_Prop18 = {
   0x6211 /* first character */
  ,0x6211 /* last character  */
  ,&GUI_Font16_CharInfo[111] /* address of first character */
  ,&GUI_Font16_Prop19 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font16_Prop17 = {
   0x60A8 /* first character */
  ,0x60A8 /* last character  */
  ,&GUI_Font16_CharInfo[110] /* address of first character */
  ,&GUI_Font16_Prop18 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font16_Prop16 = {
   0x606F /* first character */
  ,0x606F /* last character  */
  ,&GUI_Font16_CharInfo[109] /* address of first character */
  ,&GUI_Font16_Prop17 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font16_Prop15 = {
   0x5E08 /* first character */
  ,0x5E08 /* last character  */
  ,&GUI_Font16_CharInfo[108] /* address of first character */
  ,&GUI_Font16_Prop16 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font16_Prop14 = {
   0x5B66 /* first character */
  ,0x5B66 /* last character  */
  ,&GUI_Font16_CharInfo[107] /* address of first character */
  ,&GUI_Font16_Prop15 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font16_Prop13 = {
   0x5B50 /* first character */
  ,0x5B50 /* last character  */
  ,&GUI_Font16_CharInfo[106] /* address of first character */
  ,&GUI_Font16_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font16_Prop12 = {
   0x597D /* first character */
  ,0x597D /* last character  */
  ,&GUI_Font16_CharInfo[105] /* address of first character */
  ,&GUI_Font16_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font16_Prop11 = {
   0x5947 /* first character */
  ,0x5947 /* last character  */
  ,&GUI_Font16_CharInfo[104] /* address of first character */
  ,&GUI_Font16_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font16_Prop10 = {
   0x5929 /* first character */
  ,0x5929 /* last character  */
  ,&GUI_Font16_CharInfo[103] /* address of first character */
  ,&GUI_Font16_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font16_Prop9 = {
   0x5927 /* first character */
  ,0x5927 /* last character  */
  ,&GUI_Font16_CharInfo[102] /* address of first character */
  ,&GUI_Font16_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font16_Prop8 = {
   0x5404 /* first character */
  ,0x5404 /* last character  */
  ,&GUI_Font16_CharInfo[101] /* address of first character */
  ,&GUI_Font16_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font16_Prop7 = {
   0x5316 /* first character */
  ,0x5316 /* last character  */
  ,&GUI_Font16_CharInfo[100] /* address of first character */
  ,&GUI_Font16_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font16_Prop6 = {
   0x52A8 /* first character */
  ,0x52A8 /* last character  */
  ,&GUI_Font16_CharInfo[ 99] /* address of first character */
  ,&GUI_Font16_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font16_Prop5 = {
   0x4FE1 /* first character */
  ,0x4FE1 /* last character  */
  ,&GUI_Font16_CharInfo[ 98] /* address of first character */
  ,&GUI_Font16_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font16_Prop4 = {
   0x4F4D /* first character */
  ,0x4F4D /* last character  */
  ,&GUI_Font16_CharInfo[ 97] /* address of first character */
  ,&GUI_Font16_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font16_Prop3 = {
   0x4E0E /* first character */
  ,0x4E0E /* last character  */
  ,&GUI_Font16_CharInfo[ 96] /* address of first character */
  ,&GUI_Font16_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font16_Prop2 = {
   0x3002 /* first character */
  ,0x3002 /* last character  */
  ,&GUI_Font16_CharInfo[ 95] /* address of first character */
  ,&GUI_Font16_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font16_Prop1 = {
   0x0020 /* first character */
  ,0x007E /* last character  */
  ,&GUI_Font16_CharInfo[  0] /* address of first character */
  ,&GUI_Font16_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Font16 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Font16_Prop1}
  ,14 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,11 /* Height of capital characters */
};



#endif
